[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"
healthcheckPath = "/api/products/"
healthcheckTimeout = 30
restartPolicyType = "on_failure"